# Generated by Django 6.0.2 on 2026-03-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reinforce_interval_days', models.IntegerField(default=365)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField()),
                ('next_dose', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='pets.pet')),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_vaccines', to='vaccines.vaccinetype')),
            ],
        ),
    ]
